SAP/karma-ui5

src/mockserver.js
Fixes #1:
Uncaught ReferenceError: module is not defined
at /node_modules/karma-openui5/lib/mockserver.js:7
I hereby declare to agree to the OpenUI5 Individual Contributor License
Agreement.
=> Fix: Mockserver (module is not defined)

.gitignore, Gruntfile.js, README.md, lib/index.js, src/autorun.js, src/autorun.wrapper
Test modules can be defined in the openui5 config and will be loaded
automatically via sap.ui.require.
So a custom "karma-main.js" is not require anymore, but can still be
used to manually load and run tests.
=> Add autorun feature

package.json
This actually worked, as the module comes as transitive dependency from @ui5/project.
=> [FIX] Add missing dependency to "js-yaml"

lib/client/discovery.js, package.json, test/integration/library-ui5-tooling-multiple-testsuites/karma.conf.js, test/integration/library-ui5-tooling-multiple-testsuites/package.json, test/integration/library-ui5-tooling-multiple-testsuites/src/sap/test/lib/library.js, test/integration/library-ui5-tooling-multiple-testsuites/test/.dotfile, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/foo/test.qunit.html, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/test.qunit.html, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/test.qunit.js, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/testsuite.foo.qunit.html, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/testsuite.foo.qunit.js, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/testsuite.qunit.html, test/integration/library-ui5-tooling-multiple-testsuites/test/sap/test/lib/qunit/testsuite.qunit.js, test/integration/library-ui5-tooling-multiple-testsuites/ui5.yaml
Testsuites might be using top.jsUnitTestSuite to get the testsuite
class. Therefore both it should be available in "parent" and "top".
=> [FIX] TypeError: top.jsUnitTestSuite is not a constructor

lib/client/browser.js
For debugging reasons it is helpful that the last test page is not
closed but kept open.
=> [FIX] Keep last test page open

package-lock.json, package.json, webpack.config.js
This reduces the list of dependencies required to be installed by
consumers of this plugin and makes sure to create the bundle before
publishing instead.
=> [FIX] Don't create webpack bundle on postinstall

lib/client/.eslintrc.js, lib/client/browser.js, lib/client/discovery.js, test/integration.test.js, test/integration/application-ui5-tooling-error-handling/karma-empty-testsuite.conf.js, test/integration/application-ui5-tooling-error-handling/karma-initial-testsuite-not-found.conf.js, test/integration/application-ui5-tooling-error-handling/karma-testpage-QUnit-not-loaded.conf.js, test/integration/application-ui5-tooling-error-handling/karma-testpage-not-found.conf.js, test/integration/application-ui5-tooling-error-handling/karma-testsuite-promise-reject.conf.js, test/integration/application-ui5-tooling-error-handling/package.json, test/integration/application-ui5-tooling-error-handling/ui5.yaml, test/integration/application-ui5-tooling-error-handling/webapp/test/empty-testsuite/testsuite.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/empty-testsuite/testsuite.qunit.js, test/integration/application-ui5-tooling-error-handling/webapp/test/testpage-QUnit-not-loaded/test.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/testpage-QUnit-not-loaded/testsuite.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/testpage-QUnit-not-loaded/testsuite.qunit.js, test/integration/application-ui5-tooling-error-handling/webapp/test/testpage-not-found/testsuite.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/testpage-not-found/testsuite.qunit.js, test/integration/application-ui5-tooling-error-handling/webapp/test/testsuite-promise-reject/testsuite.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/testsuite-promise-reject/testsuite.qunit.js
Fixes https://github.com/SAP/karma-ui5/issues/101
=> Improve error handling and add tests

lib/client/browser.js
Fixes: https://github.com/SAP/karma-ui5/issues/92
=> [FIX] Fix link in testsuite error messages

lib/framework.js, test/__mocks__/@ui5/server.js
Removes usage of private API.
The middlewareRepository has been introduced with ui5-server v1.2.0:
https://github.com/SAP/ui5-server/compare/v1.1.3...v1.2.0
=> [INTERNAL] Use ui5-server middlewareRepository

lib/errors.js, lib/framework.js, test/unit/framework.test.js
This PR addresses #162. 
Instead of preventing the use of `karma-ui5` with all other Karma plugins, this PR introduces a blacklist of certain plugins that are not compatible with `karma-ui5`. These plugins currently include `qunit` and `sinon`.
/cc @CCFenner
=> Allow usage with non-blacklisted karma plugins

lib/framework.js, test/unit/framework.test.js
Using an agent with "keepAlive" improves performance when proxing
requests, especially on Windows.
=> [FIX] Improve performance when serving UI5 resources via URL

lib/client/browser.js, test/integration/application-proxy/webapp/test/test.qunit.js
Code instrumented by istanbul introduces global variables
(cov_* for each file and a global __coverage__ variable).
This causes a failure when the "noglobals" QUnit config is active and
some file is loaded during a test as this pollutes the global namespace.
Hooking into the "after" function allows to add those variables to the
list of known globals so that they won't be detected as new globals.
=> [FIX] HTML mode: QUnit.config.noglobals with coverage enabled

README.md
I had some trouble the other day setting up karma-ui5 in script mode.
I was missing a minimum running example for script mode.
After half a day try-and-error, I found one.
Maybe you also find this helpful for the readme.
I also moved the "mode" section out of "Options" because I think is is a crucial option that stands above all the other options.
=> Readme: Move mode section one level up, add minimum running example for script mode

README.md, lib/client/browser.js, lib/errors.js, lib/framework.js, test/integration/application-ui5-tooling-error-handling/karma-failOnEmptyTestPage-false.conf.js, test/integration/application-ui5-tooling-error-handling/karma-failOnEmptyTestPage-true.conf.js, test/integration/application-ui5-tooling-error-handling/karma-failOnEmptyTestPage-with-script-mode.conf.js, test/integration/application-ui5-tooling-error-handling/webapp/test/empty-testpage/empty.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/empty-testpage/test.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/empty-testpage/testsuite.qunit.html, test/integration/application-ui5-tooling-error-handling/webapp/test/empty-testpage/testsuite.qunit.js, test/unit/framework.test.js
https://github.com/SAP/karma-ui5/issues/226
Hi colleagues,
In S4 if some team has qunit and opa tests defined and loaded but OPA tests contains no tests or assertion, than runner should fail with error of "Suite with no tests should be removed". This happened when someone comment out testfiles in Alljourneys and runner still loads Alljourney but than reports no tests. In this case we see low coverages and team complains about it. So we want to configure runner so that we centrally can define some parameter in karma conf file to enable or disable failure in case of no tests.
Thanks
=> [FEATURE] Add "failOnEmptyTestPage" option

test/integration/application-ui5-tooling-error-handling/karma-failOnEmptyTestPage-false.conf.js, test/integration/application-ui5-tooling-error-handling/karma-failOnEmptyTestPage-true.conf.js
PR #228 did not fail because the SauceLabs API key (or any other secure
variable) is not available in builds that are triggered from a fork.
=> [INTERNAL] Fix SauceLabs integration tests

lib/errors.js, lib/framework.js, test/unit/framework.test.js
use appropriate terminology "incompatible", because the frameworks in the list are incompatible and should therefore be excluded.
Successor of #163
=> [INTERNAL] Replace insensitive terms with inclusive language

lib/framework.js, lib/index.js, test/unit/framework.test.js, test/unit/index.test.js, test/unit/jest.config.js
Recent changes in commit 762cde2e389c5293295377c8c372e1711d17bb14 caused that always the same UI5 middleware was returned, even for multiple KarmaServer instances. Karma however, initializes the plugins for each KarmaServer instance, which causes the same middleware to be added twice to the sub-router introduced in the mentioned commit. All in all this causes unexpected behaviour in tests, e.g. failing requests when sending PATCH requests.
=> [FIX] Creating multiple plugin instances

.github/workflows/saucelabs.yml, test/integration/saucelabs.js
UI5 dropped IE11 support starting with 1.88, which caused the existing
IE11 tests via SauceLabs to fail.
Now using 1.71 which still supports IE11 and is a long-term maintenance
release.
=> [INTERNAL] SauceLabs: Run tests for IE11 with UI5 1.71

lib/client/discovery.js
With https://github.com/SAP/openui5/commit/b8569e7a26ace55f68fad905ec4f5e22ba7a22d1, the set of possible 'signatures' of testsuites has been extended in OpenUI5. The discovery needs to be adapted to this extended set.
=> [FIX] Adapt discovery to recent changes in OpenUI5

package-lock.json, package.json
Prevents regression 'TypeError: item.node is not a function' with newer
webpack versions (5.47+).
=> [INTERNAL] Pin license-webpack-plugin to 2.3.18

package-lock.json
v1.4.1 has been removed from npm
=> [INTERNAL] package-lock.json: Use colors@1.4.0

.github/workflows/github-ci.yml, .github/workflows/saucelabs.yml
Dropping old Node.js versions to allow upgrading dependencies such as
puppeteer. This is a preparation for the next major release which will
drop support for old Node.js versions.
=> [INTERNAL] Update GitHub Actions CI

.eslintrc.js, package-lock.json, package.json, test/integration/jest.config.js
BREAKING CHANGE:
Support for older Node.js and npm releases has been dropped.
Only Node.js ^16.18.0 or >=18.0.0, and npm v8 or higher are supported.
=> [BREAKING] Require Node.js ^16.18.0 || >=18.0.0 / npm >= 8

.github/in-solidarity.yml
This enables the advanced in-solidarity check which is already active for the UI5 Tooling repositories.
**Details:**
The inclusive language check is using https://github.com/ietf/terminology instead of the default set. With that more terms are declared as non inclusive.
=> [INTERNAL] Enable enhanced inclusive language check

.github/dependabot.yml
Aligned with the dependabot config of the UI5 Tooling repositories.
=> [INTERNAL] Enforce correct commit message header for dependabot updates

lib/fileExportReporter.js, package-lock.json, package.json, test/unit/fileExportReporter.js
The recursive option is available since Node v10.12, which makes the
use of thirdparty packages obsolete for most use cases.
=> [INTERNAL] Use native fs.mkdir instead of mkdirp

package.json
Follow-up of https://github.com/SAP/karma-ui5/pull/507 with alignments
based on latest changes of UI5 Tooling v3 Node.js requirements.
BREAKING CHANGE:
Raising the minimum required Node v18 version to 18.12.0.
=> [BREAKING] Require Node.js ^16.18.0 || >=18.12.0

package-lock.json, package.json
Introduced via c0164c7aef4d6c40255004d4fc5d4a817b973f63 to meet the
peerDependency of eslint-plugin-jest.
Jest has been removed in favor f ava via
https://github.com/SAP/karma-ui5/pull/511 so it is not needed anymore.
=> [INTERNAL] Remove unused typescript devDependency

lib/client/browser.cjs, test/integration/application-ui5-tooling-url-parameters/webapp/test/test.qunit.js, test/integration/application-ui5-tooling-url-parameters/webapp/test/testsuite.qunit.js, test/integration/integration.js
Some testsuites may define url parameters for a test and expect the
order of parameters to be unchanged.
It is not fully clear for which cases the sorting has been implemented
initially but it has been decided to rather check for those issues
instead of always sort to have the same order in every browser.
BCP: 2370044253
=> [FIX] Ensure defined urlParameters order

lib/framework.js, test/unit/framework.js
fixes: https://github.com/SAP/karma-ui5/issues/595
=> [FIX] Consider configPath when autoDetectType

ava.config.js
Recent changes in Node 20 have also been down-ported to 18.19.0.
See: https://github.com/SAP/ui5-server/pull/602
=> [INTERNAL] Fix coverage setup in newer Node versions

.github/workflows/github-ci.yml, .github/workflows/saucelabs.yml, package.json
BREAKING CHANGE:
Support for older Node.js and npm releases has been dropped.
Only Node.js 20.11.x and >=22.0.0 as well as npm v8 or higher are supported.
JIRA: CPOUI5FOUNDATION-846
=> [BREAKING] Drop node v16, v18, v21
